bazar/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'catalog.views.handler404'
handler500 = 'catalog.views.handler500'

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

catalog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.item_list, name='index'),
    path('user/<int:user_id>', views.user_page, name='user_page'),
    url(r'^user/user_settings', views.user_settings, name='user_settings'),
    url(r'^user/items', views.items, name='items'),
    url(r'^user/delete_user', views.delete_user, name='delete_user'),
    path('user/delete_item/<int:item_id>', views.delete_item, name='delete_item'),
    path('user/edit_item/<int:item_id>', views.edit_item, name='edit_item'),
    path('user/edit_item/<int:item_id>/delete/images/<str:image_name>', views.edit_item, name='edit_item'),
    path('item/<int:item_id>', views.item_detail, name='item_detail'),
    path('add_item/', views.add_item, name='add_item'),
    url(r'^observe/$', views.observe, name='observe'),
    url(r'^user/observed', views.observed, name='observed'),
    url(r'^stopobserving/$', views.stopobserving, name='stopobserving'),
    url(r'^login/$', views.login_page, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
    url(r"^messages/inbox/", views.InboxView.as_view(), name="inbox"),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify
from django_summernote.fields import SummernoteTextField

class User(AbstractUser):
    user_phonenumber = models.IntegerField(unique=False, null=True, blank=True)
    observing = models.CharField(max_length=200, null=True, default=None)

class Item(models.Model):
    item_id = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=200)
    item_price = models.DecimalField(max_digits=12, decimal_places=2)
    item_description = SummernoteTextField(max_length=500)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return str(self.pk) + " " + self.item_name + " " + str(self.pub_date)

def get_image_filename(instance, filename):
    item_id = instance.item.id
    slug = slugify(item_id)
    return "images/%s-%s" % (slug, filename)

class Images(models.Model):
    item = models.ForeignKey(Item, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename, verbose_name='Image')

catalog/forms.py
from django import forms
from .models import User, Item, Images
from django.core.exceptions import ValidationError


class DataForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'user_phonenumber', 'observing']


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label="Nazwa użytkownika")
    email = forms.EmailField(label="E-mail")
    password1 = forms.CharField(label='Wprowadz haslo', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Potwierdz hasło', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Login jest już zajęty!")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("Podany e-mail już istnieje.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Hasła różnią się od siebie.")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_price', 'item_description', ]


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Images
        fields = ('image',)

catalog/views.py
# -*- coding: utf-8 -*-
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.cache import cache
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, AuthenticationForm, SetPasswordForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib import messages
from django.http import HttpResponse
from django.template import loader
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.forms import modelformset_factory
from .models import Item, User, Images
from .helpers import user_is_not_logged_in
from .forms import DataForm, ItemForm, CustomUserCreationForm, ImageForm
from social_django.models import UserSocialAuth
from sorl.thumbnail import delete as delete_thumbnail
from pinax.messages.models import Thread, Message
import datetime, os, random
from django.shortcuts import render


def handler404(request, exception=None):
    return render(request, 'catalog/404.html', {})


def handler500(request, exception=None):
    return render(request, 'catalog/500.html', {})

# CONSTS ##############################################################################################################


images_quantity = 4
randomize_items_time = 1200


# MAIN PAGE ###########################################################################################################

def user_page(request, user_id):
    user_items = Item.objects.filter(item_id_id=user_id)
    user_details = User.objects.get(id=user_id)
    template = loader.get_template('catalog/user.html')
    context = {
        'user_items': user_items,
        'user_details': user_details
    }
    return HttpResponse(template.render(context, request))


@user_passes_test(user_is_not_logged_in, login_url='index')
def login_page(request):
    if request.method == 'POST':
        create_user_form = CustomUserCreationForm(request.POST)
        login_form = AuthenticationForm(request=request, data=request.POST)
        if 'register' in request.POST and create_user_form.is_valid():
            create_user_form.save()
            messages.success(request, 'Pomyślnie zarejestrowano!')
            return redirect('login')
        if 'login' in request.POST and login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Pomyślnie zalogowano!')
                return redirect('index')
            else:
                messages.success(request, 'Nie znaleziono użytkownika!')
        elif 'login' in request.POST and not login_form.is_valid():
            messages.error(request, 'Login lub hasło niepoprawne.')
        return redirect('login')
    else:
        create_user_form = CustomUserCreationForm()
        login_form = AuthenticationForm()
    template = loader.get_template('catalog/login.html')
    context = {
        'create_user_form': create_user_form,
        'login_form': login_form,
    }
    return HttpResponse(template.render(context, request))


def item_detail(request, item_id):
    images_count = None
    try:
        item_details = Item.objects.get(id=item_id)
        item_images = Images.objects.filter(item_id=item_id)
        images_count = range(len(item_images))
        user_details = User.objects.get(id=item_details.item_id_id)
        user_id = item_details.item_id_id
    except Exception:
        item_details = user_details = item_images = user_id = None
    template = loader.get_template('catalog/item.html')

    if request.method == 'POST':
        if 'to_user' in request.POST and 'from_user' in request.POST and 'content' in request.POST:
            to_user = User.objects.get(id=request.POST['to_user'])
            message = Message.new_message(from_user=request.user, to_users=[to_user], subject=request.POST['subject'], content=request.POST['content'])
            message.thread.userthread_set.filter(user=request.user).update(deleted=False)
            messages.info(request, "Wiadomość została wysłana")
    context = {
        'item_details': item_details,
        'user_details': user_details,
        'item_images': item_images,
        'user_id': user_id,
        'images_count': images_count,
    }
    if item_details is None:
        messages.warning(request, "Przedmiot najprawdopodobniej nie jest już dostępny")
        cache.delete('items_list')
        return redirect('index')
    return HttpResponse(template.render(context, request))


def item_list(request):
    if not cache.get('items_list'):
        items_list = sorted(Item.objects.order_by('-pub_date'), key=lambda x: random.random())
    else:
        items_list = cache.get('items_list')
    cache.set('items_list', list(items_list), randomize_items_time)

    paginator = Paginator(items_list, 3)
    page = request.GET.get('page')
    try:
        list_of_items = paginator.page(page)
    except PageNotAnInteger:
        list_of_items = paginator.page(1)
    except EmptyPage:
        list_of_items = paginator.page(paginator.num_pages)

    item_images = []
    for item in list_of_items:
        items_images = Images.objects.filter(item_id=item.id)
        if not items_images:
            item_images.append([])
        else:
            item_images.append([item_image for item_image in items_images][0])

    template = loader.get_template('catalog/index.html')
    context = {
        'items': zip(list_of_items, item_images),
        'items_list': list_of_items,
    }
    return HttpResponse(template.render(context, request))


# ITEMS ###############################################################################################################

def add_item(request):
    template = loader.get_template('catalog/add_item.html')
    context = {}
    if request.user.is_authenticated:
        imageformset = modelformset_factory(Images, form=ImageForm, extra=images_quantity)
        if request.method == 'POST':
            form_add_item = ItemForm(request.POST, instance=User())
            formset = imageformset(request.POST, request.FILES, queryset=Images.objects.none())
            request.encoding = 'utf-8'
            if form_add_item.is_valid() and formset.is_valid():
                item = Item(
                    item_id_id=request.user.pk,
                    pub_date=datetime.datetime.now(),
                    item_name=form_add_item.cleaned_data['item_name'],
                    item_price=float(form_add_item.cleaned_data['item_price']),
                    item_description=form_add_item.cleaned_data['item_description'],
                )
                item.save()
                for form in formset.cleaned_data:
                    if form:
                        image = form['image']
                        photo = Images(item=item, image=image)
                        photo.save()
                messages.success(request, 'Przedmiot został dodany!')
                cache.delete('items_list')
                return redirect('items')
            elif not form_add_item.is_valid() or not formset.is_valid():
                context = {
                    'form_add_item': form_add_item,
                    'formset': formset,
                }
                messages.error(request, 'Napotkano błędy!')
                if form_add_item.errors:
                    messages.error(request, form_add_item.errors)
                return HttpResponse(template.render(context, request))
        else:
            form_add_item = ItemForm()
            formset = imageformset(queryset=Images.objects.none())
        context = {
            'form_add_item': form_add_item,
            'formset': formset,
        }
    return HttpResponse(template.render(context, request))


@login_required
def items(request):
    user_items = Item.objects.filter(item_id_id=request.user.pk)
    user_details = User.objects.get(id=request.user.pk)
    template = loader.get_template('catalog/items.html')
    context = {
        'user_items': user_items,
        'user_details': user_details
    }
    return HttpResponse(template.render(context, request))


@login_required
def edit_item(request, item_id, image_name=None):
    instance = Item.objects.filter(id=int(item_id))
    try:
        if int(request.user.pk) == int(instance.values('item_id_id')[0]['item_id_id']):
            template = loader.get_template('catalog/edit_item.html')
            instance = Item.objects.get(id=int(item_id))
            form_edit_item = ItemForm(initial={
                'item_name': instance.item_name,
                'item_price': instance.item_price,
                'item_description': instance.item_description
            })

            images = Images.objects.filter(item_id=int(item_id))
            image_form_set = modelformset_factory(Images, form=ImageForm, extra=images_quantity - len(images))
            images_form_set = image_form_set(queryset=Images.objects.none())
            context = {
                'form_edit_item': form_edit_item,
                'images': images,
                'formset': images_form_set,
            }
            if image_name:
                image = Images.objects.get(image=str('images/' + image_name))
                delete_thumbnail(image.image.path)
                image.delete()
                images = Images.objects.filter(item_id=int(item_id))
                context['images'] = images
                image_form_set = modelformset_factory(Images, form=ImageForm, extra=images_quantity - len(images))
                images_form_set = image_form_set(queryset=Images.objects.none())
                context['formset'] = images_form_set
                instance = Item.objects.filter(id=int(item_id))

catalog/templates/pinax/messages/base.html
{% extends "catalog/base.html" %}

catalog/templates/pinax/messages/inbox.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% load i18n %}
    {% load pinax_messages_tags %}
    <div class="pinax-messages-inbox-container">
        <div class="container"><br>
            <h1 class="with-actions">
                Wiadomości
            </h1>
            <section class="mailbox">
                <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Temat wiadomości</th>
                            <th>Użytkownicy</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for thread in threads %}
                        <div class="thread {% if thread|unread:user %} unread {% endif %}">
                            <tr>
                                <td>
                                    <div class="latest-message">
                                        <a href="{{thread.get_absolute_url}}">
                                            {% if thread|unread:user %} <b style="color:#e2a545; display: inline"> Nowa wiadomość! </b> {% endif %}
                                            <div style="display: inline;" class="subject">{{ thread.subject|safe }}</div>
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    <div class="participants"> {{ thread.users.all|join:", " }}</div>
                                </td>
                            </tr>
                        </div>
                        {% empty %}
                            <div class="no-messages">Nie masz wiadomości.</div>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

catalog/templates/pinax/messages/message_create.html
{% extends 'catalog/item.html' %}
{% block content %}
{% endblock %}

catalog/templates/pinax/messages/thread_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container" style="text-align: center"><br>
    <div class="pinax-messages-delete-container">
        <h2>{% block head_title %}Potwierdź usunięcie wątku: {{ thread.subject|safe }}{% endblock %}</h2>
        {% url "pinax_messages:thread_delete" thread.pk as post_url %}

        <div class="delete-warning" role="alert">
            {% load i18n %}
            {% trans "Jesteś pewien, że chcesz usunąć ten wątek?" %}
        </div>

        <form action="{{ post_url }}" method="POST">
            {% csrf_token %}
            <div class="form-actions">
                <a class="btn btn-info" href="{% url "pinax_messages:inbox" %}" class="cancel">{% trans "Anuluj" %}</a>
                <button class="btn btn-danger">{% trans "Usuń" %}</button>
            </div>
        </form>
    </div>
    </div>
{% endblock %}

catalog/templates/pinax/messages/thread_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="pinax-messages-thread-detail-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="with-actions" style="text-align: center">
                    {{ thread.subject|safe }}
                </h1>
            </div>
            <div class="col-sm-4">
                {% for message in thread.messages.all %}
                    <h6>({{ message.sent_at }})</h6>
                    <h3 style="display: inline"><b>{{ message.sender.username }}</b> napisał:</h3>
                    <i>{{ message.content|urlize|linebreaks }}</i>
                {% endfor %}
            </div>
            <div class="col-sm-8">
                <form class="comment-form" action="{% url "pinax_messages:thread_detail" thread.pk %}" method="post">
                    <div class="form-group">
                        {% csrf_token %}
                        <div class="form-group">
                            {% load widget_tweaks %}
                            <h3>Odpowiedź:</h3> {{ form.content|add_class:"form-control" }}
                        </div>
                        <div class="form-actions">
                            <a class="btn btn-info" href="{% url "pinax_messages:inbox" %}" class="cancel">Anuluj</a>
                            <button class="btn btn-primary" type="submit">Wyślij</button>
                            <a style="float: right" class="btn btn-danger" href="{% url "pinax_messages:thread_delete" thread.pk %}">Usuń cały wątek</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
    </div>
{% endblock %}